#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d         

bspc config border_width         3
bspc config window_gap          24

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#4c566a"
bspc config focused_border_color "#c1666a"

$HOME/.config/polybar/launch.sh

pgrep -f polkit-gnome-authentication-agent-1 > /dev/null || /usr/libexec/polkit-gnome-authentication-agent-1 &
pgrep -x nitrogen > /dev/null || nitrogen --restore
pgrep -x picom > /dev/null || picom &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x volumeicon > /dev/null || (sleep 2 && (volumeicon &))

